-- GENRES
INSERT INTO PUBLIC.GENRES (GENRE_ID,GENRE_NAME)
	SELECT * FROM (SELECT 1 AS GENRE_ID, 'Комедия' AS GENRE_NAME) AS TEMP
	WHERE NOT EXISTS (SELECT GENRE_ID FROM PUBLIC.GENRES WHERE GENRE_ID = 1)
	LIMIT 1;
INSERT INTO PUBLIC.GENRES (GENRE_ID,GENRE_NAME)
	SELECT * FROM (SELECT 2 AS GENRE_ID, 'Драма' AS GENRE_NAME) AS TEMP
	WHERE NOT EXISTS (SELECT GENRE_ID FROM PUBLIC.GENRES WHERE GENRE_ID = 2)
	LIMIT 1;
INSERT INTO PUBLIC.GENRES (GENRE_ID,GENRE_NAME)
	SELECT * FROM (SELECT 3 AS GENRE_ID, 'Мультфильм' AS GENRE_NAME) AS TEMP
	WHERE NOT EXISTS (SELECT GENRE_ID FROM PUBLIC.GENRES WHERE GENRE_ID = 3)
	LIMIT 1;
INSERT INTO PUBLIC.GENRES (GENRE_ID,GENRE_NAME)
	SELECT * FROM (SELECT 4 AS GENRE_ID, 'Триллер' AS GENRE_NAME) AS TEMP
	WHERE NOT EXISTS (SELECT GENRE_ID FROM PUBLIC.GENRES WHERE GENRE_ID = 4)
	LIMIT 1;
INSERT INTO PUBLIC.GENRES (GENRE_ID,GENRE_NAME)
	SELECT * FROM (SELECT 5 AS GENRE_ID, 'Документальный' AS GENRE_NAME) AS TEMP
	WHERE NOT EXISTS (SELECT GENRE_ID FROM PUBLIC.GENRES WHERE GENRE_ID = 5)
	LIMIT 1;
INSERT INTO PUBLIC.GENRES (GENRE_ID,GENRE_NAME)
	SELECT * FROM (SELECT 6 AS GENRE_ID, 'Боевик' AS GENRE_NAME) AS TEMP
	WHERE NOT EXISTS (SELECT GENRE_ID FROM PUBLIC.GENRES WHERE GENRE_ID = 6)
	LIMIT 1;
	
-- RATINGS
INSERT INTO PUBLIC.MPA (MPA_ID,MPA_NAME)
	SELECT * FROM (SELECT 0 AS MPA_ID, 'Unnknown' AS MPA_NAME) AS TEMP
	WHERE NOT EXISTS (SELECT MPA_ID FROM PUBLIC.MPA WHERE MPA_ID = 0)
	LIMIT 1;
INSERT INTO PUBLIC.MPA (MPA_ID,MPA_NAME)
	SELECT * FROM (SELECT 1 AS MPA_ID, 'G' AS MPA_NAME) AS TEMP
	WHERE NOT EXISTS (SELECT MPA_ID FROM PUBLIC.MPA WHERE MPA_ID = 1)
	LIMIT 1;
INSERT INTO PUBLIC.MPA (MPA_ID,MPA_NAME)
	SELECT * FROM (SELECT 2 AS MPA_ID, 'PG' AS MPA_NAME) AS TEMP
	WHERE NOT EXISTS (SELECT MPA_ID FROM PUBLIC.MPA WHERE MPA_ID = 2)
	LIMIT 1;
INSERT INTO PUBLIC.MPA (MPA_ID,MPA_NAME)
	SELECT * FROM (SELECT 3 AS MPA_ID, 'PG-13' AS MPA_NAME) AS TEMP
	WHERE NOT EXISTS (SELECT MPA_ID FROM PUBLIC.MPA WHERE MPA_ID = 3)
	LIMIT 1;
INSERT INTO PUBLIC.MPA (MPA_ID,MPA_NAME)
	SELECT * FROM (SELECT 4 AS MPA_ID, 'R' AS MPA_NAME) AS TEMP
	WHERE NOT EXISTS (SELECT MPA_ID FROM PUBLIC.MPA WHERE MPA_ID = 4)
	LIMIT 1;
INSERT INTO PUBLIC.MPA (MPA_ID,MPA_NAME)
	SELECT * FROM (SELECT 5 AS MPA_ID, 'NC-17' AS MPA_NAME) AS TEMP
	WHERE NOT EXISTS (SELECT MPA_ID FROM PUBLIC.MPA WHERE MPA_ID = 5)
	LIMIT 1;

-- STATUSES
INSERT INTO PUBLIC.STATUSES (STATUS_ID,STATUS_NAME)
	SELECT * FROM (SELECT 1 AS STATUS_ID, 'Запрос в друзья (дружба не пеподтверждена)' AS STATUS_NAME) AS TEMP
	WHERE NOT EXISTS (SELECT STATUS_ID FROM PUBLIC.STATUSES WHERE STATUS_ID = 1)
	LIMIT 1;
INSERT INTO PUBLIC.STATUSES (STATUS_ID,STATUS_NAME)
	SELECT * FROM (SELECT 2 AS STATUS_ID, 'Друзья (дружба подтверждена)' AS STATUS_NAME) AS TEMP
	WHERE NOT EXISTS (SELECT STATUS_ID FROM PUBLIC.STATUSES WHERE STATUS_ID = 2)
	LIMIT 1;